# A list of journals

Created 2020.10.19 / Updated 2020.11.17

In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [2]:
name = '20201016_wykaz.xlsx'

In [3]:
df = pd.read_excel(name, sheet_name='Czasopisma',header=1)
df.shape

(29037, 52)

# THE FIRST ROWS OF THE TABLE

In [4]:
df.head()

Lp.         Tytul1       issn     e-issn        Tytul2     issn.1  \
0    1   2D Materials  2053-1583  2053-1583  2D Materials        NaN   
1    2      3 Biotech  2190-572X  2190-5738     3 Biotech  2190-572X   
2    3     3C Empresa  2254-3376  2254-3376           NaN        NaN   
3    4  3c Tecnologia  2254-4143  2254-4143           NaN        NaN   
4    5         3C Tic  2254-6529  2254-6529           NaN        NaN   

    e-issn.1  Punkty  101  102  ...  510  511  601  602  603  604  605  606  \
0  2053-1583     140  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN    x    x   
1  2190-5738      70  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN    x  NaN  NaN   
2        NaN      20  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3        NaN      20  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
4        NaN      20  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   607  701  
0  NaN  NaN  
1  NaN  NaN  
2  NaN  NaN  
3  NaN  NaN  
4  NaN  NaN  

[5 rows x 52 columns]

# ALL COLUMN NAMES

In [5]:
df.columns

Index([     'Lp.',   'Tytul1',     'issn',   'e-issn',   'Tytul2',   'issn.1',
       'e-issn.1',   'Punkty',        101,        102,        103,        104,
              105,        106,        107,        201,        202,        203,
              204,        205,        206,        207,        208,        209,
              301,        302,        303,        304,        401,        402,
              403,        404,        405,        501,        502,        503,
              504,        505,        506,        507,        508,        509,
              510,        511,        601,        602,        603,        604,
              605,        606,        607,        701],
      dtype='object')

# AVAILIABLE POINT VALUES IN THE TABLE

In [6]:
sorted(df.Punkty.unique())

[20, 40, 70, 100, 140, 200]

# CHOOSING A COLUMN WHICH IS POTENTIALLY OF OUR INTEREST

In [7]:
col0 = ['issn', 'e-issn', 'tytul1', 'tytul2', 'punkty']
col1 = ['automatyka, elektronika i elektrotechnika','informatyka techniczna i telekomunikacja', 'inżynieria biomedyczna',]
col2 = ['nauki medyczne', 'nauki o zdrowiu','informatyka', 'matematyka', 'nauki biologiczne']
my_columns = col0 + col1 + col2
#my_columns

# READ COLUMN NAMES AND THEIR CODES (IN POLISH)

In [8]:
codes = ['Tytul1', 'Tytul2', 'Punkty', 202,203,204,302, 304,602,603,604]
data = dict(zip(codes,my_columns))
data

{'Tytul1': 'issn',
 'Tytul2': 'e-issn',
 'Punkty': 'tytul1',
 202: 'tytul2',
 203: 'punkty',
 204: 'automatyka, elektronika i elektrotechnika',
 302: 'informatyka techniczna i telekomunikacja',
 304: 'inżynieria biomedyczna',
 602: 'nauki medyczne',
 603: 'nauki o zdrowiu',
 604: 'informatyka'}

# CODE DESCRIPTION (WITH ENGLISH TRANSLATION)

1. 'Tytul1': 'tytul1', - **title1**
1. 'Tytul2': 'tytul2', - **title2**
1. 'Punkty': 'punkty', - **points**
1. 202: 'automatyka, elektronika i elektrotechnika', - **automatics, electronics and electroenergetic**
1. 203: 'informatyka techniczna i telekomunikacja', - **computer science and telecomunications**
1. 204: 'inżynieria biomedyczna', - **BIOMEDICAL ENGINEERING (!!!!!!)**
1. 302: 'nauki medyczne', - **MEDICAL SCIENCE**
1. 304: 'nauki o zdrowiu', -**HEALTH SCIENCE**
1. 602: 'informatyka', - **COMPUTER SCIENCE**
1. 603: 'matematyka', - **MATHEMATICS**
1. 604: 'nauki biologiczne'} - **BIOLOGICAL SCIENCE**

---

# TITLES FROM BIOMEDCIAL ENG. DOMAIN

In [9]:
codes_short = ['issn', 'e-issn','Tytul1', 'Tytul2', 'Punkty', 204]
df1 = df[codes_short].copy()
print(df1.shape)
df1.head()

(29037, 6)


issn     e-issn         Tytul1        Tytul2  Punkty  204
0  2053-1583  2053-1583   2D Materials  2D Materials     140    x
1  2190-572X  2190-5738      3 Biotech     3 Biotech      70    x
2  2254-3376  2254-3376     3C Empresa           NaN      20  NaN
3  2254-4143  2254-4143  3c Tecnologia           NaN      20    x
4  2254-6529  2254-6529         3C Tic           NaN      20    x

### REMOVE NaN IN 204 (BIOMEDICAL ENG.) COLUMN

In [41]:
idx = df1[[204]].dropna(axis=0, how='any').index

In [42]:
df2 = df1.loc[idx,:]
df2.sort_values(by=['Punkty'], inplace=True, ascending=False)
df2.shape

(10641, 6)

### REPLACE ALL TITLES TO LOWERCASE LETTERS

In [51]:
#df["first_column"] = df["first_column"].str.lower()
df2['Tytul1'] = df2['Tytul1'].str.lower()
df2['Tytul2'] = df2['Tytul2'].str.lower()
print(df2.shape)
df2.head()

(10641, 6)


issn     e-issn  \
20914  1523-9829  1545-4274   
970    1073-449X  1535-4970   
3375   1550-4131  1932-7420   
3377   2211-1247  2211-1247   
3378   1001-0602  1748-7838   

                                                  Tytul1  \
20914            annual review of biomedical engineering   
970    american journal of respiratory and critical c...   
3375                                     cell metabolism   
3377                                        cell reports   
3378                                       cell research   

                                                  Tytul2  Punkty 204  
20914                                                NaN     200   x  
970    american journal of respiratory and critical c...     200   x  
3375                                     cell metabolism     200   x  
3377                                        cell reports     200   x  
3378                                       cell research     200   x

### 1. POINT NUMBER CONDITION (EQUALLED TO 100 POINTS)

In [52]:
df3 = df2[df2['Punkty'] == 100]
print(df3.shape)
df3.head(30)

(1678, 6)


issn     e-issn  \
14932  1541-6933  1556-0961   
5161   0012-4486  1573-2622   
11150  1757-1146        NaN   
14518  1044-7431  1095-9327   
14517  0303-7207        NaN   
10098  0165-2370  1873-250X   
9016   1201-9712  1878-3511   
14525  1059-1524  1939-4586   
5845   2050-7887  2050-7895   
4772   1070-5287  1531-6971   
9552   0883-0185  1563-5244   
10099  0267-9477  1364-5544   
10105  0021-8782  1469-7580   
5837   0013-9351  1096-0953   
5833   0269-7491  1873-6424   
10326  0925-2738  1573-5001   
4773   1040-8711  1531-6963   
9576   0969-6016  1475-3995   
5862   1755-4365        NaN   
5827   1758-2229  1758-2229   
10328  1672-6529  1672-6529   
14476  1383-469X  1572-8153   
9578   0937-3462  1433-3023   
14921  0197-4580  1558-1497   
5878   1525-5050  1525-5069   
5010   2233-6079  2233-6087   
11189  1091-255X  1873-4626   
5874   1750-1911  1750-192X   
11185  0815-9319  1440-1746   
4763   1040-8746  1531-703X   

                                                  Tytul1  \
14932                                 neurocritical care   
5161                           documenta ophthalmologica   
11150                 journal of foot and ankle research   
14518                molecular and cellular neuroscience   
14517               molecular and cellular endocrinology   
10098        journal of analytical and applied pyrolysis   
9016        international journal of infectious diseases   
14525                      molecular biology of the cell   
5845           environmental science-processes & impacts   
4772               current opinion in pulmonary medicine   
9552                 international reviews of immunology   
10099          journal of analytical atomic spectrometry   
10105                                 journal of anatomy   
5837                              environmental research   
5833                             environmental pollution   
10326                        journal of biomolecular nmr   
4773                     current opinion in rheumatology   
9576   international transactions in operational rese...   
5862                                           epidemics   
5827                  environmental microbiology reports   
10328                      journal of bionic engineering   
14476                     mobile networks & applications   
9578                 international urogynecology journal   
14921                              neurobiology of aging   
5878                                 epilepsy & behavior   
5010                       diabetes & metabolism journal   
11189                journal of gastrointestinal surgery   
5874                                         epigenomics   
11185         journal of gastroenterology and hepatology   
4763                         current opinion in oncology   

                                                  Tytul2  Punkty 204  
14932                                 neurocritical care     100   x  
5161                           documenta ophthalmologica     100   x  
11150                 journal of foot and ankle research     100   x  
14518               molecular and cellular neurosciences     100   x  
14517               molecular and cellular endocrinology     100   x  
10098        journal of analytical and applied pyrolysis     100   x  
9016        international journal of infectious diseases     100   x  
14525                      molecular biology of the cell     100   x  
5845       environmental sciences: processes and impacts     100   x  
4772               current opinion in pulmonary medicine     100   x  
9552                 international reviews of immunology     100   x  
10099          journal of analytical atomic spectrometry     100   x  
10105                                 journal of anatomy     100   x  
5837                              environmental research     100   x  
5833                             environmental pollution     100   x  
10326                        journal of biomolecular 

### SEARCH FOR A SPECIFIED WORD IN A NAME

In [54]:
df4 = df3[df3.Tytul1.str.contains('resonan')]
print(df4.shape)
df4

(5, 6)


issn     e-issn                                  Tytul1  \
11698  1053-1807  1522-2586   journal of magnetic resonance imaging   
11697  1090-7807  1096-0856           journal of magnetic resonance   
13816  0730-725X  1873-5894              magnetic resonance imaging   
13820  0740-3194  1522-2594          magnetic resonance in medicine   
18696  0926-2040  1527-3326  solid state nuclear magnetic resonance   

                                       Tytul2  Punkty 204  
11698   journal of magnetic resonance imaging     100   x  
11697           journal of magnetic resonance     100   x  
13816              magnetic resonance imaging     100   x  
13820          magnetic resonance in medicine     100   x  
18696  solid state nuclear magnetic resonance     100   x